// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Umi-qJ288eW33L5UC7v-4Aal4YRO38E',
    appId: '1:495100884012:web:751f91c0ae5450dc2acd89',
    messagingSenderId: '495100884012',
    projectId: 'inclass13-80873',
    authDomain: 'inclass13-80873.firebaseapp.com',
    storageBucket: 'inclass13-80873.firebasestorage.app',
    measurementId: 'G-W8CCFVD4XW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGVsFZ7cVv-o8TGBBev1Tqf4N7qVSOSys',
    appId: '1:495100884012:android:46c077711ed449432acd89',
    messagingSenderId: '495100884012',
    projectId: 'inclass13-80873',
    storageBucket: 'inclass13-80873.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5kwmSR6ClN7fgDmhKcDTcbmbIlafY3nQ',
    appId: '1:495100884012:ios:e08ba3e4d11f308e2acd89',
    messagingSenderId: '495100884012',
    projectId: 'inclass13-80873',
    storageBucket: 'inclass13-80873.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5kwmSR6ClN7fgDmhKcDTcbmbIlafY3nQ',
    appId: '1:495100884012:ios:e08ba3e4d11f308e2acd89',
    messagingSenderId: '495100884012',
    projectId: 'inclass13-80873',
    storageBucket: 'inclass13-80873.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Umi-qJ288eW33L5UC7v-4Aal4YRO38E',
    appId: '1:495100884012:web:cdd8b5fd4214a9bd2acd89',
    messagingSenderId: '495100884012',
    projectId: 'inclass13-80873',
    authDomain: 'inclass13-80873.firebaseapp.com',
    storageBucket: 'inclass13-80873.firebasestorage.app',
    measurementId: 'G-2YSC4H0DPT',
  );
}
